<script setup>
// GENERATED by tools/gen-filters.mjs from assets/animatio-filters.svg.
// DO NOT EDIT. Run `npm run docs:filters` after changing the sprite.
//
// A CSS package cannot ship DOM, so every an-svg-* class needs this in the
// page (§9.5). The docs site performs the install step exactly as it tells
// consumers to. Without it, an-svg-goo and friends render nothing.
</script>

<template>
  <svg xmlns="http://www.w3.org/2000/svg" width="0" height="0" aria-hidden="true"
       focusable="false" style="position:absolute;width:0;height:0;overflow:hidden;pointer-events:none">
    <defs>
  
      <filter id="an-goo" color-interpolation-filters="sRGB">
        <feGaussianBlur in="SourceGraphic" stdDeviation="10" result="blur"/>
        <feColorMatrix in="blur" mode="matrix"
          values="1 0 0 0 0
                  0 1 0 0 0
                  0 0 1 0 0
                  0 0 0 20 -9" result="goo"/>
        <feBlend in="SourceGraphic" in2="goo"/>
      </filter>
  
      <filter id="an-glass-real" color-interpolation-filters="sRGB">
        <feTurbulence type="fractalNoise" baseFrequency="0.008 0.012"
                      numOctaves="2" seed="7" result="noise"/>
        <feGaussianBlur in="noise" stdDeviation="2" result="soft"/>
        <feDisplacementMap in="SourceGraphic" in2="soft" scale="40"
                           xChannelSelector="R" yChannelSelector="G"/>
      </filter>
  
      </defs>
  </svg>
</template>
