#!/usr/bin/env node
// Animatio — regenerate the docs site's copy of the SVG filter sprite.
//
// The site must paste the sprite (§9.5) or every an-svg-* class renders
// nothing. Generating the component from assets/animatio-filters.svg means the
// site cannot drift from the sprite it documents.
//
//   npm run docs:filters

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1");

const svg = readFileSync(join(ROOT, "assets/animatio-filters.svg"), "utf8")
  .replace(/<\?xml[^>]*\?>\s*/, "")
  .replace(/<!--[\s\S]*?-->\s*/g, "")
  .trim();

const body = svg.split("\n").map((l) => "  " + l).join("\n");

writeFileSync(
  join(ROOT, "docs/.vitepress/theme/components/AnFilters.vue"),
  `<script setup>
// GENERATED by tools/gen-filters.mjs from assets/animatio-filters.svg.
// DO NOT EDIT. Run \`npm run docs:filters\` after changing the sprite.
//
// A CSS package cannot ship DOM, so every an-svg-* class needs this in the
// page (§9.5). The docs site performs the install step exactly as it tells
// consumers to. Without it, an-svg-goo and friends render nothing.
</${"script"}>

<template>
${body}
</template>
`
);

const ids = [...svg.matchAll(/<filter[^>]*id="([^"]+)"/g)].map((m) => m[1]);
console.log(`animatio: docs sprite -> ${ids.length} filters (${ids.join(", ")})`);
